image: "node:10.16"

stages:
  - install
  - lint

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install --frozen-lockfile --ignore-engines

lint:
  stage: lint
  script:
    - yarn lint
