image: "node:10.16"

stages:
  - install
  - lint
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install:
  stage: install
  script:
    - yarn install --frozen-lockfile --ignore-engines

lint:
  stage: lint
  cache:
    policy: pull
  script:
    - yarn lint

test:
  stage: test
  cache:
    policy: pull
  script:
    - echo "todo..."

build:
  stage: build
  cache:
    policy: pull
  script:
    - yarn build

deploy:
  stage: deploy
  cache:
    policy: pull
  only:
    refs:
      - master
  script:
    echo "todo..."
